2021-03-14 21:22:00,930 INFO    MainThread:33920 [wandb_setup.py:_flush():70] setting env: {}
2021-03-14 21:22:00,930 INFO    MainThread:33920 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-03-14 21:22:00,930 INFO    MainThread:33920 [wandb_setup.py:_flush():70] setting login settings: {}
2021-03-14 21:22:00,930 INFO    MainThread:33920 [wandb_init.py:_log_setup():318] Logging user logs to /home/cdminix/Documents/MLP/drought/wandb/run-20210314_212200-5xlpasxc/logs/debug.log
2021-03-14 21:22:00,930 INFO    MainThread:33920 [wandb_init.py:_log_setup():319] Logging internal logs to /home/cdminix/Documents/MLP/drought/wandb/run-20210314_212200-5xlpasxc/logs/debug-internal.log
2021-03-14 21:22:01,980 INFO    MainThread:33920 [wandb_run.py:_console_start():1396] atexit reg
2021-03-14 21:22:01,980 INFO    MainThread:33920 [wandb_run.py:_redirect():1259] redirect: SettingsConsole.REDIRECT
2021-03-14 21:22:01,981 INFO    MainThread:33920 [wandb_run.py:_redirect():1264] Redirecting console.
2021-03-14 21:22:01,981 INFO    MainThread:33920 [redirect.py:install():213] install start
2021-03-14 21:22:01,981 INFO    MainThread:33920 [redirect.py:install():228] install stop
2021-03-14 21:22:01,981 INFO    MainThread:33920 [redirect.py:install():213] install start
2021-03-14 21:22:01,982 INFO    MainThread:33920 [redirect.py:install():228] install stop
2021-03-14 21:22:01,982 INFO    MainThread:33920 [wandb_run.py:_redirect():1310] Redirects installed.
2021-03-14 21:28:03,705 ERROR   stderr    :33920 [redirect.py:_pipe_relay():139] problem in pipe relay
Traceback (most recent call last):
  File "/home/cdminix/anaconda3/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 137, in _pipe_relay
    cb(name, data)
  File "/home/cdminix/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 723, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/home/cdminix/anaconda3/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 153, in publish_output
    self._publish_output(o)
  File "/home/cdminix/anaconda3/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 158, in _publish_output
    self._publish(rec)
  File "/home/cdminix/anaconda3/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 457, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2021-03-14 21:28:10,519 INFO    MainThread:33920 [wandb_run.py:_atexit_cleanup():1366] got exitcode: 1
2021-03-14 21:28:10,519 INFO    MainThread:33920 [wandb_run.py:_restore():1338] restore
2021-03-14 21:28:10,519 INFO    MainThread:33920 [redirect.py:uninstall():232] uninstall start
2021-03-14 21:28:10,519 INFO    MainThread:33920 [redirect.py:_stop():287] _stop: stdout
2021-03-14 21:28:10,519 INFO    MainThread:33920 [redirect.py:_stop():293] _stop closed: stdout
2021-03-14 21:28:10,519 INFO    stdout    :33920 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2021-03-14 21:28:10,519 INFO    stdout    :33920 [redirect.py:_pipe_relay():145] relay done done: stdout
2021-03-14 21:28:10,520 INFO    MainThread:33920 [redirect.py:_stop():299] _stop joined: stdout
2021-03-14 21:28:10,520 INFO    MainThread:33920 [redirect.py:_stop():301] _stop rd closed: stdout
2021-03-14 21:28:10,520 INFO    MainThread:33920 [redirect.py:uninstall():236] uninstall done
2021-03-14 21:28:10,520 INFO    MainThread:33920 [redirect.py:uninstall():232] uninstall start
2021-03-14 21:28:10,520 INFO    MainThread:33920 [redirect.py:_stop():287] _stop: stderr
2021-03-14 21:28:10,520 INFO    MainThread:33920 [redirect.py:_stop():293] _stop closed: stderr
2021-03-14 21:28:10,520 INFO    stderr    :33920 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2021-03-14 21:28:10,520 INFO    stderr    :33920 [redirect.py:_pipe_relay():145] relay done done: stderr
2021-03-14 21:28:10,520 INFO    MainThread:33920 [redirect.py:_stop():299] _stop joined: stderr
2021-03-14 21:28:10,520 INFO    MainThread:33920 [redirect.py:_stop():301] _stop rd closed: stderr
2021-03-14 21:28:10,520 INFO    MainThread:33920 [redirect.py:uninstall():236] uninstall done
2021-03-14 21:28:10,520 INFO    MainThread:33920 [wandb_run.py:_restore():1338] restore
2021-03-14 21:28:10,879 INFO    MainThread:33920 [internal.py:handle_exit():139] Internal process exited
